#name: 10-azure-docker-build-push
#
#on:
#  create:
#    branches:
#      - '*'
#    tags:
#      - '*'
#  push:
#    tags:
#      - '**'
#      - v**
#  workflow_run:
#    workflows: [11-auto-versioning]
#    types:
#      - completed
#
#
#jobs:
#  build-push-docker:
#    runs-on: ubuntu-latest
#    strategy:
#      fail-fast: false
#      matrix:
#        services:
#          - /apps/backends/next-server
#          - /apps/frontends/admin-console
#          - /apps/services/the-analytics-service
#          - /apps/frontends/the-editor
#          - /apps/services/the-initialization-service
#          - /apps/services/the-microservice
#          - /apps/services/the-pdf-converter
#          - /apps/services/the-pdf-converter-viewport
#          - /apps/services/the-video-renderer
#          - /apps/services/the-video-renderer-viewport
#          - /apps/frontends/the-viewer
#    permissions:
#      contents: read
#      packages: write
#      id-token: write
#
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v4
#
#      - name: Setup Docker buildx
#        uses: docker/setup-buildx-action@v3
#
#      - name: Show versions
#        run: |
#          docker version
#          docker buildx version
#
#      - name: Get Tag Name
#        id: tag_name
#        run: |
#          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
#
#      - name: Show Tag Name
#        env:
#          VERSION: ${{ steps.tag_name.outputs.SOURCE_TAG }}
#        run: |
#          echo "Tag is: ${VERSION}"
#
##      - name: Docker build and push with login
##        env:
###          VERSION: ${{ steps.tag_name.outputs.SOURCE_TAG }}
##          SERVICES: ${{ matrix.services }}
##          LOGIN-SERVER: assemblysuite.azurecr.io
##          AZURE_REGISTRY_USERNAME: ${{ secrets.AZURE_REGISTRY_USERNAME }}
##          AZURE_REGISTRY_PASSWORD: ${{ secrets.AZURE_REGISTRY_PASSWORD }}
##        run: |
##          echo "run build and push for service: ${SERVICES} with version: ${VERSION}"
##          chmod u+x ./.github/scripts/build-and-push-container.sh
##          ./.github/scripts/build-and-push-container.sh \
##            --servicePath "${SERVICES}" \
##            --dockerRegistry 'assemblysuite.azurecr.io' \
##            --dockerRegistryPathPrefix 'snapshot' \
##            --version test.0.1.3 \
##            --dockerLoginUsername "${AZURE_REGISTRY_USERNAME}" \
##            --dockerLoginpassword "${AZURE_REGISTRY_PASSWORD}" \
##            --profil ci
