name: 10-azure-docker-build-push

on:
  create:
    branches:
      - '*'
    tags:
      - '*'
  push:
    tags:
      - '**'
      - v**
  workflow_run:
    workflows: [11-auto-versioning]
    types:
      - completed


jobs:
  build-push-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get Tag Name
        id: tag_name
        run: |
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}

      - name: Show Tag Name
        env:
          VERSION: ${{ steps.tag_name.outputs.SOURCE_TAG }}
        run: |
          echo "Tag is: ${VERSION}"
