name: 10-azure-docker-build-push

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - '**'
      - v**


jobs:
  patch-tag:
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.tag_version.outputs.new_tag || steps.tag_name.outputs.source_tag }}
    steps:
      - uses: actions/checkout@v4

      - name: Get Tag Name
        id: tag_name
        if: startsWith(github.ref, 'refs/tags/')
        run: echo "source_tag=${GITHUB_REF#refs/tags/}" >> "$GITHUB_OUTPUT"

      - name: Bump version and push tag
        if: startsWith(github.ref, 'refs/tags/') != true
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: v
          dry_run: false
          default_bump: patch

      - name: Create a GitHub release
        if: startsWith(github.ref, 'refs/tags/') != true
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}


  build-push-docker:
    runs-on: ubuntu-latest
    needs:
      - patch-tag
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show Tag Name
        env:
          VERSION: ${{ needs.patch-tag.outputs.new_tag }}
        run: |
          echo "Tag is: ${VERSION}"

  deploy:
    runs-on: ubuntu-latest
    needs:
      - patch-tag
      - build-push-docker
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show Tag Name
        env:
          VERSION: ${{ needs.patch-tag.outputs.new_tag }}
        run: |
          echo "Tag is: ${VERSION}"
